### ISSUE TITLE
Yo, brah, give us the ability to add our own trains

### ISSUE THREAD

**Issue by indiesquidge** [dalexj/food_train#3]
So in order to make this a true democracy and not a dictatorship on what we can vote on for lunch, I'm thinking you need to add in the ability for everyone to start a train, not just the creator of a given group.

**Comment by dglunz** [comment]
Please give a detailed rationale for this "democracy" feature.

**Comment by trayo** [comment]
:+1:

**Comment by gravitinos** [comment]
alex rulez

**Comment by indiesquidge** [comment]
@dglunz, because no one wants to be part of a dictatorship, and everyone wants to be part of a democracy. The point of the app is to crowd source the most popular choice for lunch, but what happens when you hate all the options? Sucks to suck. You don't even get the chance to make a claim yourself. Without adding in the ability for everyone to suggest preferences, you introduce an apathy that will eventually become the app's demise.

**Comment by jgujgu** [comment]
![screen shot 2015-01-27 at 4 32 13 pm](https://cloud.githubusercontent.com/assets/5934106/5929574/26c61b6a-a642-11e4-9da6-d94c9f30bca9.png)
